enum telemetryKeys {
  ASSET_ENTITY_TYPE_KEY = 'ASSET',
  ASSET_PROFILE_ENTITY_TYPE_KEY = 'ASSET_PROFILE',
  DEVICE_ENTITY_TYPE_KEY = 'DEVICE',
  DEVICE_PROFILE_ENTITY_TYPE_KEY = 'DEVICE_PROFILE',
  ALARM_ENTITY_TYPE_KEY = 'ALARM',
  USER_ENTITY_TYPE_KEY = 'USER',
  PERMISSION_ENTITY_TYPE_KEY = 'PERMISSION',
  EQUIPMENT_ENTITY_TYPE_KEY = 'EQUIPMENT',
  AREA_ENTITY_TYPE_KEY = 'AREA',
  REPAIR_TOOLS_ENTITY_TYPE_KEY = 'REPAIR_TOOLS',
  REPLACEMENT_PARTS_ENTITY_TYPE_KEY = 'REPLACEMENT_PARTS',
  CUSTOMER_ENTITY_TYPE_KEY = 'CUSTOMER',
  PARTNER_ENTITY_TYPE_KEY = 'PARTNER',
  SERVER_SCOPE_KEY = 'SERVER_SCOPE',
  CLIENT_SCOPE_KEY = 'CLIENT_SCOPE',
  SHARED_SCOPE_KEY = 'SHARED_SCOPE',
}

export default telemetryKeys
